# Linear Algebra Basics with Numpy 

In [32]:
import numpy as np

# Creating Numpy Matrices

In [33]:
A = np.matrix([[1.,2],[3,4],[5,6]])
print(A)
B = np.matrix([[1.,2],[3,4],[5,6]])
print('\n')
print(A)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


[[1. 2.]
 [3. 4.]
 [5. 6.]]


# Vector is a One Dimensional Matrix 

In [34]:
x = np.matrix('1,2')
print(x)
print('\n')
print(x.T)

[[1 2]]


[[1]
 [2]]


# Matrix Matrix and Vector Matrix Multiplication

In [35]:
x = np.matrix('4.,5.')
print(x)
print('\n')
A = np.matrix([[1.0,2],[3,4],[5,6]])
B = np.matrix([[2,3],[1,5],[4,7]])
print(A)
print('\n')
print(B)
print('\n')
print(A*x.T)
print('\n')
print(A*B.T)

[[4. 5.]]


[[1. 2.]
 [3. 4.]
 [5. 6.]]


[[2 3]
 [1 5]
 [4 7]]


[[14.]
 [32.]
 [50.]]


[[ 8. 11. 18.]
 [18. 23. 40.]
 [28. 35. 62.]]


In [36]:
print(x[0,0],x[0,1])

4.0 5.0


# Rank of a Matrix

In [37]:
A = np.ones((4,3))
print(A)
print(np.linalg.matrix_rank(A))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1


# Vector Matrix Dot Product

In [38]:
A = np.matrix([[1,2],[3,4]])
print(A)
b = np.array([10,20])
print(b)
print(np.dot(A,b))

[[1 2]
 [3 4]]
[10 20]
[[ 50 110]]


# Solve Equations like Ax = b with numpy.linalg

In [39]:
from numpy.linalg import solve

In [40]:
A = np.matrix([[1,2],[3,4]])
b = np.array([10,20])
x = solve(A,b)
print(x)

[0. 5.]


# Eigen Values and Eigen Vectors

In [41]:
from numpy.linalg import eig

In [42]:
A = np.matrix([[1,2],[3,4]])
#print(eig(A))# there are two tuples in the result the first shows the eigen values and the second for eigen vectors
print('\n')
eig_val,eig_vector = eig(A)
print(eig_val)
print('\n')
print(eig_vector)



[-0.37228132  5.37228132]


[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# Matrix Decompositions

LU Decomposition and Gaussian Elemination

In [43]:
#A = np.matrix([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
#P, L, U = np.linalg.lu(A)
#print(P)
#print('\n')
#print(L)
#print('\n')
#print(U)

Cholesky Decomposition

In [44]:
A = np.matrix([[2,-1,0],[-1,2,-1],[0,-1,2]])
np.linalg.cholesky(A)

matrix([[ 1.41421356,  0.        ,  0.        ],
        [-0.70710678,  1.22474487,  0.        ],
        [ 0.        , -0.81649658,  1.15470054]])

QR Decomposition

In [46]:
np.linalg.qr(A)

(matrix([[-0.89442719, -0.35856858,  0.26726124],
         [ 0.4472136 , -0.71713717,  0.53452248],
         [-0.        ,  0.5976143 ,  0.80178373]]),
 matrix([[-2.23606798,  1.78885438, -0.4472136 ],
         [ 0.        , -1.67332005,  1.91236577],
         [ 0.        ,  0.        ,  1.06904497]]))

Singular Value Decomposition

In [47]:
np.linalg.svd(A)

(matrix([[-5.00000000e-01, -7.07106781e-01,  5.00000000e-01],
         [ 7.07106781e-01, -3.32148455e-16,  7.07106781e-01],
         [-5.00000000e-01,  7.07106781e-01,  5.00000000e-01]]),
 array([3.41421356, 2.        , 0.58578644]),
 matrix([[-5.00000000e-01,  7.07106781e-01, -5.00000000e-01],
         [-7.07106781e-01,  2.24174877e-16,  7.07106781e-01],
         [ 5.00000000e-01,  7.07106781e-01,  5.00000000e-01]]))

In [48]:
#

In [49]:
#

# Reshaping an Array

In [50]:
sample_matrix = np.matrix([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

# Reshaping 4x3 matrix to 2x6 matrix

In [51]:
print(sample_matrix)
print('\n')
print(sample_matrix.reshape(2,6))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# Matrix Inverse

In [52]:
sample_matrix = np.matrix([[1,4],[2,5]])
print(np.linalg.inv(sample_matrix))

[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]


# Identity Matrix

In [53]:
identity_matrix = np.matrix([[1,0,0],[0,1,0],[0,0,1]])
identity_matrix_inv = np.linalg.inv(identity_matrix)
print(identity_matrix)
print('\n')
print(identity_matrix_inv)
print('\n')
print(identity_matrix*identity_matrix_inv)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Diagonal Elements and Trace of a Matrix

In [54]:
sample_matrix = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(sample_matrix.diagonal())
print('\n')
print(sample_matrix.diagonal().sum())

[[1 5 9]]


15


# Flatten a Matrix

In [55]:
print(sample_matrix.flatten())

[[1 2 3 4 5 6 7 8 9]]


# Determinant of a Matrix

In [45]:
print(np.linalg.det(sample_matrix))

NameError: name 'sample_matrix' is not defined