# Linear Algebra Basics with Numpy 

In [2]:
import numpy as np

Creating Numpy Matrices

In [3]:
A = np.matrix([[1.,2],[3,4],[5,6]])
print(A)
B = np.matrix([[1.,2],[3,4],[5,6]])
print('\n')
print(A)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


[[1. 2.]
 [3. 4.]
 [5. 6.]]


Vector as a One Dimensional Matrix 

In [4]:
x = np.matrix('1,2')
print(x)
print('\n')
print(x.T)

[[1 2]]


[[1]
 [2]]


Matrix and Vector Multiplication

In [5]:
x = np.matrix('4.,5.')
print(x)
A = np.matrix([[1.0,2],[3,4],[5,6]])
print(A)
print(A*x.T)

[[4. 5.]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[14.]
 [32.]
 [50.]]


In [6]:
print(x[0,0],x[0,1])

4.0 5.0


Rank of a Matrix

In [7]:
A = np.ones((4,3))
print(A)
print(np.linalg.matrix_rank(A))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1


Vector Matrix Dot Product

In [8]:
A = np.matrix([[1,2],[3,4]])
print(A)
b = np.array([10,20])
print(b)
print(np.dot(A,b))

[[1 2]
 [3 4]]
[10 20]
[[ 50 110]]


Solve Equations like Ax = b with numpy.linalg

In [9]:
from numpy.linalg import solve

In [10]:
A = np.matrix([[1,2],[3,4]])
b = np.array([10,20])
x = solve(A,b)
print(x)

[0. 5.]


Eigen Values and Eigen Vectors

In [11]:
from numpy.linalg import eig

In [12]:
A = np.matrix([[1,2],[3,4]])
#print(eig(A))# there are two tuples in the result the first shows the eigen values and the second for eigen vectors
print('\n')
eig_val,eig_vector = eig(A)
print(eig_val)
print('\n')
print(eig_vector)



[-0.37228132  5.37228132]


[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# Vectors Matrices and Arrays

Transpose a Vector or a Matrix

In [23]:
sample_vector = np.array([1,2,3,4,5,6])
sample_matrix = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

print(sample_vector.T)
print('\n')
print(sample_matrix.T)

[1 2 3 4 5 6]


[[1 4 7]
 [2 5 8]
 [3 6 9]]


Reshaping an Array

In [24]:
sample_matrix = np.matrix([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

Reshaping 4x3 matrix to 2x6 matrix

In [25]:
print(sample_matrix)
print('\n')
print(sample_matrix.reshape(2,6))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
