# Linear Algebra Basics with Numpy 

In [4]:
import numpy as np

Creating Numpy Matrices

In [5]:
A = np.matrix([[1.,2],[3,4],[5,6]])
print(A)
B = np.matrix([[1.,2],[3,4],[5,6]])
print('\n')
print(A)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


[[1. 2.]
 [3. 4.]
 [5. 6.]]


Vector as a One Dimensional Matrix 

In [6]:
x = np.matrix('1,2')
print(x)
print('\n')
print(x.T)

[[1 2]]


[[1]
 [2]]


Matrix and Vector Multiplication

In [7]:
x = np.matrix('4.,5.')
print(x)
A = np.matrix([[1.0,2],[3,4],[5,6]])
print(A)
print(A*x.T)

[[4. 5.]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[14.]
 [32.]
 [50.]]


In [8]:
print(x[0,0],x[0,1])

4.0 5.0


Rank of a Matrix

In [9]:
A = np.ones((4,3))
print(A)
print(np.linalg.matrix_rank(A))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1


Vector Matrix Dot Product

In [10]:
A = np.matrix([[1,2],[3,4]])
print(A)
b = np.array([10,20])
print(b)
print(np.dot(A,b))

[[1 2]
 [3 4]]
[10 20]
[[ 50 110]]
