# Linear Algebra Basics with Numpy 

In [12]:
import numpy as np

Creating Numpy Matrices

In [13]:
A = np.matrix([[1.,2],[3,4],[5,6]])
print(A)
B = np.matrix([[1.,2],[3,4],[5,6]])
print('\n')
print(A)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


[[1. 2.]
 [3. 4.]
 [5. 6.]]


Vector as a One Dimensional Matrix 

In [14]:
x = np.matrix('1,2')
print(x)
print('\n')
print(x.T)

[[1 2]]


[[1]
 [2]]


Matrix and Vector Multiplication

In [15]:
x = np.matrix('4.,5.')
print(x)
A = np.matrix([[1.0,2],[3,4],[5,6]])
print(A)
print(A*x.T)

[[4. 5.]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[14.]
 [32.]
 [50.]]


In [16]:
print(x[0,0],x[0,1])

4.0 5.0


Rank of a Matrix

In [17]:
A = np.ones((4,3))
print(A)
print(np.linalg.matrix_rank(A))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1


Vector Matrix Dot Product

In [18]:
A = np.matrix([[1,2],[3,4]])
print(A)
b = np.array([10,20])
print(b)
print(np.dot(A,b))

[[1 2]
 [3 4]]
[10 20]
[[ 50 110]]


Solve Equations like Ax = b with numpy.linalg

In [19]:
from numpy.linalg import solve

In [23]:
A = np.matrix([[1,2],[3,4]])
b = np.array([10,20])
x = solve(A,b)
print(x)

[0. 5.]


Eigen Values and Eigen Vectors

In [24]:
from numpy.linalg import eig

In [27]:
A = np.matrix([[1,2],[3,4]])
#print(eig(A))# there are two tuples in the result the first shows the eigen values and the second for eigen vectors
print('\n')
eig_val,eig_vector = eig(A)
print(eig_val)
print('\n')
print(eig_vector)



[-0.37228132  5.37228132]


[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


will change for later !